[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CornerPlotting = "4a808bcd-0da0-4a1c-a768-2071018375da"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SideKicks = "ae7baef6-f8d7-4188-9988-8bf5c4952615"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[sources]
CornerPlotting = {path = "../../CornerPlotting.jl"}
SideKicks = {path = ".."}
